version: "2"
exclude_patterns:
- "tmp/"
plugins:
  rubocop:
    enabled: true
    channel: channel/rubocop-0-63
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  flog:
    enabled: true
  eslint:
    enabled: true
  nodesecurity:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true

